[package]
name = "stubs"
version = "0.1.0"
authors = ["Julius Rup≈°ys"]
edition = "2018"

[dependencies]
ethereum-types = '0.9.2'
anyhow_stable_backtrace = { path = '../anyhow_stable_backtrace' }
types = { path = '../types' }
hashing = { path = '../hashing' }
bls = { path = '../bls' }